stadium = input("경기장은 어디입니까? ")
win_team = input("이긴 팀은 어디입니까? ")
lose_team = input("진 팀은 어디입니까? ")
vip = input("우수 선수는 누구입니까? ")
score = input("스코어는 몇대 몇입니까? ")

print("===========================")
print("오늘",stadium,"에서 야구 경기가 열렸습니다.")
print(win_team,"과 ",lose_team,"은 치열한 공방전을 펼쳤습니다.")
print(vip,"이 맹활약을 하였습니다.")
print("결국",win_team,"가",lose_team,"를",score,"로 이겼습니다.")
print("===========================")
